### PR TITLE
Fix tests on OTP 21.3

### LINKED ISSUE #153: Fix tests for OTP 21.3
Lots of failures related to the change in formatting of TLS alerts. For example:

<details>

```
  2) test ssl certificate verification bad certificate - badssl.com (Mint.IntegrationTest)
     test/mint/integration_test.exs:78
     match (=) failed
     code:  assert {:error, %TransportError{reason: {:tls_alert, 'unknown ca'}}} = HTTP.connect(:https, "untrusted-root.badssl.com", 443, transport_opts: [log_alert: false, reuse_sessions: false])
     right: {:error,
             %Mint.TransportError{
               reason: {:tls_alert,
                {:unknown_ca, 'received CLIENT ALERT: Fatal - Unknown CA'}}
             }}
     stacktrace:
       test/mint/integration_test.exs:79: (test)
```

</details>

### PR DESCRIPTION
**Pull request by whatyouhide**
Closes #153.

### CODE REVIEW

File: test/mint/integration_test.exs [hunk 1]
```diff
@@ -94,14 +100,22 @@ defmodule Mint.IntegrationTest do
...
                  443,
                  transport_opts: [log_alert: false, reuse_sessions: false]
                )
 
+      # OTP 21.3 changes the format of SSL errors. Let's support both ways for now.
+      assert reason in [
+               {:tls_alert, 'handshake failure'},
+               {:tls_alert,
+                {:handshake_failure,
+                 'received CLIENT ALERT: Fatal - Handshake Failure - {bad_cert,hostname_check_failed}'}}
```
Comment (ericmj) [inline test/mint/integration_test.exs]: Formatting? 😱

Comment (whatyouhide) [reply test/mint/integration_test.exs]: ¯\\\_(ツ)\_/¯

Comment (whatyouhide) [reply test/mint/integration_test.exs]: ¯\_(ツ)_/¯
